// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdSwqA1RHaz-Y3aZUTHk6ykv7iVOZJhR0',
    appId: '1:70411954798:web:41595b5c9ac8782518947f',
    messagingSenderId: '70411954798',
    projectId: 'rentcarapp-a2b88',
    authDomain: 'rentcarapp-a2b88.firebaseapp.com',
    storageBucket: 'rentcarapp-a2b88.appspot.com',
    measurementId: 'G-TQJ6CCE5QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFxS11A87HkYUixqFZF8Bw7QU33rlJUYc',
    appId: '1:70411954798:android:52c262ba7e810e4518947f',
    messagingSenderId: '70411954798',
    projectId: 'rentcarapp-a2b88',
    storageBucket: 'rentcarapp-a2b88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0R9hfEm1GLHhw2OT_B-AlO-dL5FFnX4',
    appId: '1:70411954798:ios:48c50a194e6d9db418947f',
    messagingSenderId: '70411954798',
    projectId: 'rentcarapp-a2b88',
    storageBucket: 'rentcarapp-a2b88.appspot.com',
    iosBundleId: 'com.example.carRentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy0R9hfEm1GLHhw2OT_B-AlO-dL5FFnX4',
    appId: '1:70411954798:ios:48c50a194e6d9db418947f',
    messagingSenderId: '70411954798',
    projectId: 'rentcarapp-a2b88',
    storageBucket: 'rentcarapp-a2b88.appspot.com',
    iosBundleId: 'com.example.carRentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdSwqA1RHaz-Y3aZUTHk6ykv7iVOZJhR0',
    appId: '1:70411954798:web:a58c173c7d14361918947f',
    messagingSenderId: '70411954798',
    projectId: 'rentcarapp-a2b88',
    authDomain: 'rentcarapp-a2b88.firebaseapp.com',
    storageBucket: 'rentcarapp-a2b88.appspot.com',
    measurementId: 'G-D62C5TB627',
  );
}
